### ISSUE TITLE
Cannot install package via opkg on OpenWRT Chaos Calmer

### ISSUE THREAD

**Issue by nemesifier** [openwisp/luci-mod-openwisp#1]
When trying to install the package with opkg with the following command:

```
opkg install http://downloads.openwisp.org/luci-mod-openwisp/la
test/ar71xx/luci-mod-openwisp_1_ar71xx.ipk
```

I get the following error:

```
Collected errors:
 * check_data_file_clashes: Package luci-mod-openwisp wants to install file /usr/lib/lua/luci/view/sysauth.htm
    But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package luci-mod-openwisp.
```

**Comment by cassioac** [comment]
I've got the same problem, is there a fix/workaround for this?

**Comment by cassioac** [comment]
I did the following:
mv /usr/lib/lua/luci/view/sysauth.htm /usr/lib/lua/luci/view/sysauth.htm2
opkg install http://downloads.openwisp.org/luci-mod-openwisp/latest/ar71xx/luci-mod-openwisp_1_ar71xx.ipk
(success)

Is this workaround OK?

**Comment by nemesifier** [comment]
Yes it's ok for the moment until we figure out if there's a better way.

**Comment by nemesifier** [comment]
d04210b should fix the issue
